// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Landmark_Remark.Migrations
{
    [DbContext(typeof(Landmark_RemarkContext))]
    partial class Landmark_RemarkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Landmark_Remark.Models.LocationMarker", b =>
                {
                    b.Property<int>("LocationMarkerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.Property<string>("Title");

                    b.Property<int>("UserID");

                    b.HasKey("LocationMarkerID");

                    b.ToTable("LocationMarker");
                });

            modelBuilder.Entity("Landmark_Remark.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserID = 5,
                            FirstName = "Altaf",
                            LastName = "Virani",
                            Password = "Altaf",
                            UserName = "Altaf"
                        },
                        new
                        {
                            UserID = 6,
                            FirstName = "Guest FName",
                            LastName = "Guest LName",
                            Password = "Guest",
                            UserName = "Guest"
                        },
                        new
                        {
                            UserID = 7,
                            FirstName = "Mark",
                            LastName = "Taylor",
                            Password = "Mark",
                            UserName = "Mark"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
